### ISSUE TITLE
i can not run my program correctly

### ISSUE THREAD

**Issue by SkyXj** [slutske22/leaflet-arrowheads#1]
i do not want to run my program by npm,but i can not find the source of leaflet-arrowheads.

**Comment by slutske22** [comment]
On the repo page, you'll see the file list.  You'll see the [src](https://github.com/slutske22/leaflet-arrowheads/tree/master/src) folder, and within that, you'll see the link to the [leaflet-arrowheads.js](https://github.com/slutske22/leaflet-arrowheads/blob/master/src/leaflet-arrowheads.js) file.

Hopefully that's a direct enough answer for you.  Just make sure you put the <script> tags in your HTML header in the right order, as explained in the instructions.

**Comment by SkyXj** [comment]
thank you for your code and answer,in fact,i saw the&nbsp; &nbsp;
code but it seem i can not use it,becase it start with "import { } from '/node_modules/leaflet-geometryutil/src/leaflet.geometryutil.js' ",





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seth Lutske"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 上午9:31
收件人: "slutske22/leaflet-arrowheads"<leaflet-arrowheads@noreply.github.com&gt;; 
抄送: "夏焌"<1012262558@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [slutske22/leaflet-arrowheads] i can not run my program correctly (#1)




On the repo page, you'll see the file list.  You'll see the src folder, and within that, you'll see the link to the leaflet-arrowheads.js file.
 
Hopefully that's a direct enough answer for you.  Just make sure you put the <script&gt; tags in your HTML header in the right order, as explained in the instructions.

**Comment by slutske22** [comment]
Oh right.  You may need to adjust the file path to wherever you have leaflet.geometryutil.js in your project.  I just assumed its in node_modules, but if you're keeping it somewhere else, you'll need to specify where.

If you're trying to avoid ES6 imports and modules completely, just cut that line out  (assuming geometryutil is linked in your HTML header before arrowheads.)  Let me know if that works.

I highly recommend getting into ES6 modules, imports and exports.  It was confusing to me at first, but it ends up opening up a much better way to organize your code and use other people's code as well.

**Comment by SkyXj** [comment]
thany you for your suggestion,if i use ES6 modules,i must&nbsp;refactoring&nbsp;the&nbsp;code.yeah，when i cut that line and cut that code is "export default",my code works correctly,Thank you again for your code




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seth Lutske"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 中午11:10
收件人: "slutske22/leaflet-arrowheads"<leaflet-arrowheads@noreply.github.com&gt;; 
抄送: "夏焌"<1012262558@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [slutske22/leaflet-arrowheads] i can not run my program correctly (#1)




Oh right.  You may need to adjust the file path to wherever you have leaflet.geometryutil.js in your project.  I just assumed its in node_modules, but if you're keeping it somewhere else, you'll need to specify where.
 
If you're trying to avoid ES6 imports and modules completely, just cut that line out  (assuming geometryutil is linked in your HTML header before arrowheads.)  Let me know if that works.
 
I highly recommend getting into ES6 modules, imports and exports.  It was confusing to me at first, but it ends up opening up a much better way to organize your code and use other people's code as well.
