### ISSUE TITLE
Property 'arrowheads' does not exist on type 'Polyline<LineString | MultiLineString, any>'

### ISSUE THREAD

**Issue by tarun1992** [slutske22/leaflet-arrowheads#12]
Hi, I am using angular and using https://github.com/Asymmetrik/ngx-leaflet wrapper to show some routes on the leaflet map.

I wanted to use arrowheads to show the routes but I am getting typescript errors "Property 'arrowheads' does not exist on type 'Polyline<LineString | MultiLineString, any>".

Any help would be appreciated.

**Comment by slutske22** [comment]
Mmmmmm yes this is a typescript issue.  I have not made a typscript declaration file for this, so it makes sense that the ts compiler is complaining, as the type definition for leaflet's `Polyline` doesn't contain an `arrowheads` property.  I'm getting heavier into the typescript these days so I'll see if I can make a .d.ts file and publish it with the next version of the package.  If you happen to be great with .d.ts files, feel free to put in a PR and I'll use it.  I may not get to this for some time, so maybe in the meantime just throw in a `// @ts-ignore` before the line where you're using `arrowheads`.

**Comment by tarun1992** [comment]
For now, I have added a @ts-ignore in my code. Will submit a PR if I do get time.

**Comment by slutske22** [comment]
I know its been like 2 years but I finally got around to writing the declarations for this.  They are available in version 1.4.0, so just upgrade your version and typescript should be happy.  [Here is a sample codesandbox](https://codesandbox.io/s/leaflet-arrowheads-ts-example-kwonf) showing use of leaflet-arrowheads with TS.
