### ISSUE TITLE
arrowheads is not a function with leaflet < 1.7.1

### ISSUE THREAD

**Issue by Fir3st** [slutske22/leaflet-arrowheads#13]
Hi,

first of all, thanks for your excellent work. 

Secondly, I have a problem with your package when I want to use it with leaflet 1.6.0. in webpack built file. It works fine with the latest version of leaflet (1.7.1), but for lower versions (even 1.7.0) I get the error "leaflet__WEBPACK_IMPORTED_MODULE_0___default.a.polyline(...).arrowheads is not a function".

import * as L from 'leaflet';
import 'leaflet-arrowheads';

const polyline = L.polyline(latLng, options)
.arrowheads({ ... });

**Comment by slutske22** [comment]
Interesting. Can you give me more details?  Is this a typescript project? Is this a compile-time error or runtime error?  Does it happen only on production builds with webpack?  Can I see the webpack config?  Help me understand exactly where / how this error is arising.

**Comment by Fir3st** [comment]
- Yes, it's TS based project
- it's runtime error when I try to display the map
- It happens with dev and also production build

```js
module.exports = (env) => ({
    devtool: 'source-map',
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
    },
    entry: {
        // non-important config
    },
    output: {
        path: path.join(__dirname, 'www/js/build'),
        filename: '[name]-[hash].js',
    },
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    cacheDirectory: true,
                    presets: ['@babel/preset-env'],
                },
            },
            {
                test: /\.ts(x?)$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'ts-loader',
                    },
                ],
            },
            {
                enforce: 'pre',
                test: /\.js$/,
                loader: 'source-map-loader',
            },
        ],
    },
    externals: {
        jquery: 'jQuery',
    },
    plugins: [
        new webpack.ProvidePlugin({
            L: 'leaflet',
            'window.L': 'leaflet',
            'L.GeometryUtil': 'leaflet-geometryutil',
        }),
        new CleanWebpackPlugin({
            cleanOnceBeforeBuildPatterns: [`${env.FILE}/**/*`],
        }),
        new WebpackAssetsManifest({
            merge: true,
            output: `${path.join(__dirname, 'www/js/build')}/manifest.json`,
        }),
    ],
});
```

**Comment by slutske22** [comment]
It looks like you're relying on webpack's `ProvidePlugin` to import your modules for you, is that right?  But you have not incuded `leaflet-arrowheads` in that list.  I'm not familiar with the subtleties of `ProvidePlugin`, but it looks like you need to name of the package as the value, and the key is the variable name that the exported contents of the package get assigned to.  However, `leaflet-arrowheads` doesn't explicity export any new values, it simply modifies the existing `L.Polyline`.  So I'm not really sure how this would fit in with `ProvidePlugin`.  Perhaps one of these?

```javascript
new webpack.ProvidePlugin({
  L: 'leaflet',
  ...
  'L.Polyline': 'leaflet-arrowheads',
  'L.Polyline.arrowheads': 'leaflet-arrowheads',
  'doesnt matter beacuse it attached to L.Polyline?': 'leaflet-arrowheads',
})
```

You can also just use a `import 'leaflet-arrowheads'` directly in your project at some point in the code execution before you use `.arrowheads()`.

In any case this is decidedly not an issue with leaflet-arrowheads, but rather with how you are trying to include it using your bundler.

**Comment by vardhan03** [comment]
@Fir3st, is this issue resolved? I am facing the same issue now.

**Comment by Fir3st** [comment]
> @Fir3st, is this issue resolved? I am facing the same issue now.

I gave it up because I switched to WebGL renderer and created my own solution.

**Comment by Fir3st** [comment]
> > @Fir3st, is this issue resolved? I am facing the same issue now.
> 
> I gave it up because I switched to WebGL renderer and created my own solution.

@Porqumn
