### ISSUE TITLE
showing truck icon instead of default plane icon

### ISSUE THREAD

**Issue by AmAngular** [slutske22/leaflet-arrowheads#19]
Hi everyone
i'm using leaflet.bezier with ngx-leaflet in my angular project and i want show truck icon instead plane icon from side view but when drawed curve line is  like valley my truck has incorrect rotate 

![Annotation 2021-06-26 001816](https://user-images.githubusercontent.com/44199773/123477962-0f574680-d614-11eb-93cc-230e457b8de5.png)

**Comment by slutske22** [comment]
I'm confused as to what this has to do with leaflet-arrowheads?

**Comment by AmAngular** [comment]
Oh i'm sorry this question is about leaflet.bezier😅😅
