### ISSUE TITLE
Incompatibility with some versions of Terser

### ISSUE THREAD

**Issue by banders** [slutske22/leaflet-arrowheads#27]
I use leaflet-arrowheads in an Angular project.  Angular builds are handled by webpack, which in turn uses the Terser library for compressing source files.  Terser seems to have trouble with one particular bit of syntax in leaflet-arrowheads 1.4.0 (line 134 of leaflet-arrowheads.js):

`if (offsets?.start || offsets?.end) {`

I think the trouble is that Terser doesn't know how to handle the optional chaining operator "?."

This is the error I get from the Angular build:

Unexpected token: punc (.) [node_modules/leaflet-arrowheads/src/leaflet-arrowheads.js:134,0][scripts.5f6e7ccbb6980d219a8b.js:930,14]

I'm using Terser 5.7.2, but I also tested with 3.16

I imagine the problem is with Terser, but perhaps leaflet-arrowheads could avoid the "?." syntax too?

**Comment by slutske22** [comment]
Optional chaining has become [pretty much standard across most browsers and javascript environments ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility), I've never had any issues compiling it with webpack.  I don't know much about angular or terser, but you'll probably need to configure it to know what to do with `?.` - this is clearly a [known issue](https://github.com/terser/terser/issues/567).
