### ISSUE TITLE
Using arrowheads with react-leaflet GeoJSON component

### ISSUE THREAD

**Issue by r0gi** [slutske22/leaflet-arrowheads#39]
Is there a simple way of using the arrowheads within a react-leaflet GeoJSON component? In your deprecated [react-leaflet-arrowheads](https://github.com/slutske22/react-leaflet-arrowheads) repo it states it can be used simply as follows:

```
<GeoJSON data={data} arrowheads={{ options }} />
```

Likewise [this issue](https://github.com/slutske22/react-leaflet-arrowheads/issues/8) states something similar.

However this doesn't seem to work for react-leaflet v4.

To complicate things slightly further, my use case has two types of geoJSON lineStrings. So ideally it would be based on a property of the lineString if the arrows show or not, rather than all lineStrings showing the arrows.

**Comment by slutske22** [comment]
What about it "doesn't seem to work"?  Do you have any code or working example of what is not working?  Does it work with vanilla leaflet with your dataset?

**Comment by r0gi** [comment]
It didn't work in the sense that the arrowheads simply weren't showing. There were no console errors etc.

However, after [forking a CodeSandbox example you made](https://codesandbox.io/s/rl-arrowheads-v2-example-forked-2kctwl?file=/src/Map.js) and updating everything to the latest react and react-leaflet, the GeoJSON component worked with the `arrowheads` prop, meaning the problem was in my local environment. I investigated potential css issues, import order, webpack config etc...

It turns out that I was running a slightly older version of leaflet, `1.9.3`, but when I installed this package, it got its own version of leaflet `1.9.4`:
```
├─┬ leaflet-arrowheads@1.4.0
│ ├─┬ leaflet-geometryutil@0.10.2
│ │ └── leaflet@1.9.4
│ └── leaflet@1.9.4
├── leaflet@1.9.3
├─┬ react-leaflet-draw@0.20.4
│ └── leaflet@1.9.3 deduped
└─┬ react-leaflet@4.2.1
  ├─┬ @react-leaflet/core@2.1.0
  │ └── leaflet@1.9.3 deduped
  └── leaflet@1.9.3 deduped
```
Simply running `yarn upgrade leaflet` fixed my problem:
```
├─┬ leaflet-arrowheads@1.4.0
│ ├─┬ leaflet-geometryutil@0.10.2
│ │ └── leaflet@1.9.4 deduped
│ └── leaflet@1.9.4 deduped
├── leaflet@1.9.4
├─┬ react-leaflet-draw@0.20.4
│ └── leaflet@1.9.4 deduped
└─┬ react-leaflet@4.2.1
  ├─┬ @react-leaflet/core@2.1.0
  │ └── leaflet@1.9.4 deduped
  └── leaflet@1.9.4 deduped
```

Regarding my second question, do you think it would be feasible or know of an easy way to conditionally show the arrows based on some property of the LineString? Happy to close this issue otherwise, thanks for getting back to me.

**Comment by slutske22** [comment]
> an easy way to conditionally show the arrows based on some property of the LineString

No.  This plugin treats `LineString`s and `MultiLineStrings` the same.

If you want to separate these out, you can render your features in a custom rendering function with [onEachFeature](https://leafletjs.com/reference.html#geojson-oneachfeature):

```
<GeoJSON
  onEachFeature={feature => {
    if (feature.type === 'LineString') {
      // or whatever
    }
  }}
/>
```
