### ISSUE TITLE
Offset from end

### ISSUE THREAD

**Issue by Alexithemia** [slutske22/leaflet-arrowheads#5]
Hey hope you are still active on this, works pretty clean and easier to implement than other similar plugins.

Just wondering if you could add a way to draw the arrow a certain distance from the end of the polyline or vertices?

Many similar libraries have this, cause some developers customize their markers the polylines point to and those overlap the arrow unless you can offset it back a bit.

Maybe allow this if they only have allVertices or endOnly option enabled? Then they can give a endOffset option of a pixel number or percentage?

**Comment by slutske22** [comment]
I think this should be relatively easy to add.  I'll try to get to it when I have some time.  Or if you feel so inclined to take a crack at it yourself, open a PR.

**Comment by mykhailovskyi** [comment]
Hi, seems to be abandoned. Any plans on this enhancement?

**Comment by slutske22** [comment]
Its not abandoned per-se, but I don't really have the time required right now to implement a feature like this.  But feel free to try it yourself and make a PR!

**Comment by Michael-372** [comment]
I have an open PR that I am looking for feedback on where I attempted to add an endoffset when using pixel size arrowheads.

https://github.com/slutske22/leaflet-arrowheads/pull/22

**Comment by slutske22** [comment]
I decided to put a little time into adding this feature.  I've come across some decisions I need to make, so I wanted to get feedback from @Michael-372  @mykhailovskyi @Alexithemia.  Is/was it needed to put an offset from the end on a single polyline, or a multipolyline?  For a multipolyline with this option, I am _guessing_ we would want the arrowheads to stop at some offset from the end for _every_ segment in a multipolyline? (When I say multipolyline, I mean a single `L.polyline` object that has an array of arrays of polylines. Each color group in the image below is like that:

<img width="781" alt="Screen Shot 2022-01-27 at 8 04 01 AM" src="https://user-images.githubusercontent.com/52637023/151396551-4aab6fb1-0bc0-4753-a54d-be08a06fc90d.png">

```js
L.polyline([
  [p1, p2, p3, etc],
  [p4, p5, p6, etc]
])
```

My expectation would be that each segment is its own entity, and each one has an offset from the end of its own self.  Would you agree?  Is this the behavior you would expect from a multipolyline?  The only alternative is that there's only an offset from the end of the last segment in the multipolyline, but I don't think that makes sense.

Thoughts?

**Comment by slutske22** [comment]
@Michael-372 @mykhailovskyi @Alexithemia This feature seems ready.  Please pull down the `@next` version of leaflet-arrowheads (`npm i leaflet-arrowheads@next`).  [Here is a codesandbox](https://codesandbox.io/s/leaflet-arrowheads-example-with-offsets-5xrse) with some offsets implemented.  There are some new docs and examples in the README on the [offsets branch](https://github.com/slutske22/leaflet-arrowheads/tree/offsets).

Let me know if this suits your purposes.  If so, I'll make it the official 1.3 release.

**Comment by Michael-372** [comment]
Awesome thanks for putting that together. I just tried it out and it seems to be working for me. Really appreciate the work. I am curious about one thing though, I see that ghost lines are being created (the solution is a bit over my head to be honest) but Im wondering about performance of drawing extra lines on the map. Im drawing 10s of thousands of these things at a time in some cases. Is it possible to use the ghost lines without adding them to the map? Im also not entire sure the ghost lines will impact performance much but every little bit counts in my case :D

Really do appreciate it again

**Comment by slutske22** [comment]
@Michael-372 I did consider that adding another line to the map for every polyline with `.arrowheads({ offset })` might impact performance.  But I figured I wouldn't worry about it until it became an issue.  Has it become an issue for you?

Arrowheads are drawn based from a polylines `._parts` property.  Leaflet updates this property every time the user zooms so that shapes are simplified when zoomed out.  In line with that, arrowheads are redrawn on every zoom as well, to match this default `L.polyline` behavior, and look good at various zoom levels.  But this property is only updated / redrawn if the polyline is actually added to the map.  That is the reason the ghosts need to be added to the map.  If you're curious, the ghosts are simply copies of the original polyline, "clipped" to the specified offsets using leaflet-geometryutil.

If you have tens of thousands of polylines on a map at once, I have to wonder what the heck you're doing, and how that could possibly be useful in displaying something on a map (from a cartographic sense).

LMK if you run into any other issues with this.  I'll give it a few days before publishing it as the official next release and closing this issue.

**Comment by Michael-372** [comment]
@slutske22  Thanks for the explanation. It will take me a few days to determine if there is any performance hit. I really appreciate the work you put in. I also agree about the number of lines on screen ha, we are doing big data analytics using plane and shipping information. The upper limit on markers/polylines is pretty high and in most cases the number will be much lower, it really just depends on user input. I'm trying to thread the needle but also push the limits on what the browser can handle vs what is actually digestible by the user.

If I notice any kind of performance degradation I will let you know :)

**Comment by slutske22** [comment]
If you're not already familiar, you may be able to improve performance by using [preferCanvas](https://leafletjs.com/reference.html#map-prefercanvas) on the map instance, or careful use of `smoothFactor` on the polylines.  

(I also wonder if mapbox might have better performance / more options for heavy data vis...)

Big data analytics through GIS visualizations sounds like fun.  Do you mind my asking what comany you're working for?

**Comment by Michael-372** [comment]
Yeah preferCanvas actually bought me a lot of performance. I'm also rending markers to the canvas as well. I've not looked into smoothFactor but I'll check it out. I'll pm you.

**Comment by Michael-372** [comment]
Forgot that you can't PM on github...

**Comment by slutske22** [comment]
slutske

**Comment by Michael-372** [comment]
Whats the 4 digit numbers after your name, discord will only let me add you directly, no lookups

**Comment by slutske22** [comment]
@Michael-372 `5446`

**Comment by slutske22** [comment]
This feature has been added in [v1.4.0](https://github.com/slutske22/leaflet-arrowheads/releases/tag/v.1.4.0).  See the README for details.
