### ISSUE TITLE
Arrow bearing is distorted on long distances

### ISSUE THREAD

**Issue by wyozi** [slutske22/leaflet-arrowheads#6]
Hi, library seems great! However, the arrow bearings seem wrong at least on the scale I'm testing on.

This is what Taipei -> Helsinki looks like with `.arrowheads({ frequency: "1000000m", size: "15px", fill: true })`
<img width="640" alt="Screenshot 2020-03-20 at 15 36 08" src="https://user-images.githubusercontent.com/4894573/77144322-8a9c8500-6ac0-11ea-81f3-1486361024ed.png">

Omitting frequency makes it look wrong, but in a different way
<img width="637" alt="Screenshot 2020-03-20 at 15 36 56" src="https://user-images.githubusercontent.com/4894573/77144375-ad2e9e00-6ac0-11ea-9e39-24325c956f70.png">

Since leaflet uses spherical mercator, I assume it is the straightforward geometrical angle calculation in `bearing` breaking on maps with small enough zoom.

**Comment by slutske22** [comment]
Interesting.  I guess I had never tested this on smaller zoom levels.  Are you using the standard leaflet projection with your map?  I will take a look at this as soon as I can, its a pretty glaring issue.  I just need to find the time.  If you have any suggestions, please let me know.

**Comment by wyozi** [comment]
Yep, as standard as it gets.

I quickly tried replacing contents of `bearing` with a simple `atan2` over `L.Projection.Mercator.project(latLng)` and it kind of worked for some polylines and didn't for others, but that might be one thing to start trying with.

**Comment by slutske22** [comment]
I fixed it.  I replaced the `L.geometryUtil.bearing` function with the `.angle` function.  You can check out [the demo](https://codesandbox.io/s/leaflet-arrowheads-example-zfxxc).  Hit the marker and click the 'To Norway' link to take you to a zoomed out map with some large polylines with correctly rendered arrowheads.  Update to version 1.1.2 and it should work.  Thank you for pointing out this glaring issue!

**Comment by wyozi** [comment]
Thanks, works great now :)

<img width="648" alt="Screenshot 2020-03-21 at 14 41 55" src="https://user-images.githubusercontent.com/4894573/77221165-38bc3380-6b82-11ea-89f5-49d9749820c9.png">
