### ISSUE TITLE
curved polyline 

### ISSUE THREAD

**Issue by Christian-Nja** [slutske22/leaflet-arrowheads#9]
Thank you for great plugin,

do you think it would be possible to add arrowheads also to other shapes like curve, for examples ones constructed with:
[https://github.com/elfalem/Leaflet.curve](url)

The problem with straight lines is that if you have two polylines 
`A -> B
 B -> A
`
One of the path would be overlapped

**Comment by slutske22** [comment]
This is a bit tricky to do in a true and correct fashion, as leaflet-arrowheads calculates arrowheads based on `latlng`s, and leaflet.curve creates its curved from svg bezier functions.

However, after toying around for a bit with it, I see that leaflet.curve offers a `.trace` function, which returns `latlng` values at specified intervals along the bezier curves.  Using this, you can create a ghost polyline, apply arrowheads to it, extract the arrowheads, and remove the ghost:

````javascript
const latlngs = pathThree.trace([0,0.1,0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])

const ghost =  L.polyline(latlngs).arrowheads({color:'orange'}).addTo(map)
const arrowheads = ghost.getArrowheads()
ghost.remove()
arrowheads.addTo(map)
````

## [Working codesandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6)

This is not.a perfect solution, as `.trace` applies the trace equally to all segments of your shape, which probably will not give you evenly spaced arrowheads.  Also, using a `frequency` other than the default (every vertex), will place arrowheads not on the line itself.  It works, but you have limitations.

I'm not clear on what you mean when you say:

> The problem with straight lines is that if you have two polylines
> `A -> B B -> A`
> One of the path would be overlapped

Trying to make leaflet-arrowheads work properly with leaflet.curve would require a total rewrite based on svg, which I don't think I'm going to do.  However, depending on your needs, using the `.trace` method to create a ghost polyline and keeping just its arrowheads may work just fine.

**Comment by Christian-Nja** [comment]
Great thank you for this, it works like a charm! 
> 
> The problem with straight lines is that if you have two polylines
> `A -> B B -> A`
> One of the path would be overlapped

what i meant was that having two straight polyline A -> B and B <- A would results in complete overlapping of the two.
I used svg to creates a curve to avoid that! That's something reasonable for example in flight path to simulate travel.
again thank you!

**Comment by slutske22** [comment]
Ah, I see what you're saying.  You're using bezier curves to differentiate between the coming and going vectors.  And you want the arrowheads in opposite directions along each curve for a nice visual.  Makes sense.  Well for a relatively simple curve like a flight path, I think the `.trace` method will work well for you.  Glad I could help.

**Comment by himanshusaraswat85** [comment]
> This is a bit tricky to do in a true and correct fashion, as leaflet-arrowheads calculates arrowheads based on `latlng`s, and leaflet.curve creates its curved from svg bezier functions.
> 
> However, after toying around for a bit with it, I see that leaflet.curve offers a `.trace` function, which returns `latlng` values at specified intervals along the bezier curves. Using this, you can create a ghost polyline, apply arrowheads to it, extract the arrowheads, and remove the ghost:
> 
> ```js
> const latlngs = pathThree.trace([0,0.1,0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
> 
> const ghost =  L.polyline(latlngs).arrowheads({color:'orange'}).addTo(map)
> const arrowheads = ghost.getArrowheads()
> ghost.remove()
> arrowheads.addTo(map)
> ```
> 
> ## [Working codesandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6)
> This is not.a perfect solution, as `.trace` applies the trace equally to all segments of your shape, which probably will not give you evenly spaced arrowheads. Also, using a `frequency` other than the default (every vertex), will place arrowheads not on the line itself. It works, but you have limitations.
> 
> I'm not clear on what you mean when you say:
> 
> > The problem with straight lines is that if you have two polylines
> > `A -> B B -> A`
> > One of the path would be overlapped
> 
> Trying to make leaflet-arrowheads work properly with leaflet.curve would require a total rewrite based on svg, which I don't think I'm going to do. However, depending on your needs, using the `.trace` method to create a ghost polyline and keeping just its arrowheads may work just fine.



> This is a bit tricky to do in a true and correct fashion, as leaflet-arrowheads calculates arrowheads based on `latlng`s, and leaflet.curve creates its curved from svg bezier functions.
> 
> However, after toying around for a bit with it, I see that leaflet.curve offers a `.trace` function, which returns `latlng` values at specified intervals along the bezier curves. Using this, you can create a ghost polyline, apply arrowheads to it, extract the arrowheads, and remove the ghost:
> 
> ```js
> const latlngs = pathThree.trace([0,0.1,0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
> 
> const ghost =  L.polyline(latlngs).arrowheads({color:'orange'}).addTo(map)
> const arrowheads = ghost.getArrowheads()
> ghost.remove()
> arrowheads.addTo(map)
> ```
> 
> ## [Working codesandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6)
> This is not.a perfect solution, as `.trace` applies the trace equally to all segments of your shape, which probably will not give you evenly spaced arrowheads. Also, using a `frequency` other than the default (every vertex), will place arrowheads not on the line itself. It works, but you have limitations.
> 
> I'm not clear on what you mean when you say:
> 
> > The problem with straight lines is that if you have two polylines
> > `A -> B B -> A`
> > One of the path would be overlapped
> 
> Trying to make leaflet-arrowheads work properly with leaflet.curve would require a total rewrite based on svg, which I don't think I'm going to do. However, depending on your needs, using the `.trace` method to create a ghost polyline and keeping just its arrowheads may work just fine.

Not a perfect solution as the arrowheads do not resize on zoom. Also, their positions go wrong on zoom.

**Comment by slutske22** [comment]
> > This is a bit tricky to do in a true and correct fashion, as leaflet-arrowheads calculates arrowheads based on `latlng`s, and leaflet.curve creates its curved from svg bezier functions.
> > However, after toying around for a bit with it, I see that leaflet.curve offers a `.trace` function, which returns `latlng` values at specified intervals along the bezier curves. Using this, you can create a ghost polyline, apply arrowheads to it, extract the arrowheads, and remove the ghost:
> > ```js
> > const latlngs = pathThree.trace([0,0.1,0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
> > 
> > const ghost =  L.polyline(latlngs).arrowheads({color:'orange'}).addTo(map)
> > const arrowheads = ghost.getArrowheads()
> > ghost.remove()
> > arrowheads.addTo(map)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## [Working codesandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6)
> > This is not.a perfect solution, as `.trace` applies the trace equally to all segments of your shape, which probably will not give you evenly spaced arrowheads. Also, using a `frequency` other than the default (every vertex), will place arrowheads not on the line itself. It works, but you have limitations.
> > I'm not clear on what you mean when you say:
> > > The problem with straight lines is that if you have two polylines
> > > `A -> B B -> A`
> > > One of the path would be overlapped
> > 
> > 
> > Trying to make leaflet-arrowheads work properly with leaflet.curve would require a total rewrite based on svg, which I don't think I'm going to do. However, depending on your needs, using the `.trace` method to create a ghost polyline and keeping just its arrowheads may work just fine.
> 
> > This is a bit tricky to do in a true and correct fashion, as leaflet-arrowheads calculates arrowheads based on `latlng`s, and leaflet.curve creates its curved from svg bezier functions.
> > However, after toying around for a bit with it, I see that leaflet.curve offers a `.trace` function, which returns `latlng` values at specified intervals along the bezier curves. Using this, you can create a ghost polyline, apply arrowheads to it, extract the arrowheads, and remove the ghost:
> > ```js
> > const latlngs = pathThree.trace([0,0.1,0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1])
> > 
> > const ghost =  L.polyline(latlngs).arrowheads({color:'orange'}).addTo(map)
> > const arrowheads = ghost.getArrowheads()
> > ghost.remove()
> > arrowheads.addTo(map)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## [Working codesandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6)
> > This is not.a perfect solution, as `.trace` applies the trace equally to all segments of your shape, which probably will not give you evenly spaced arrowheads. Also, using a `frequency` other than the default (every vertex), will place arrowheads not on the line itself. It works, but you have limitations.
> > I'm not clear on what you mean when you say:
> > > The problem with straight lines is that if you have two polylines
> > > `A -> B B -> A`
> > > One of the path would be overlapped
> > 
> > 
> > Trying to make leaflet-arrowheads work properly with leaflet.curve would require a total rewrite based on svg, which I don't think I'm going to do. However, depending on your needs, using the `.trace` method to create a ghost polyline and keeping just its arrowheads may work just fine.
> 
> <img alt="Screenshot 2022-07-21 at 12 02 00 PM" width="673" src="https://user-images.githubusercontent.com/88308646/180145213-ce08023d-aa90-491c-8e16-915a4c6ffc34.png">
> 
> Not a perfect solution as the arrowheads do not resize on zoom. Also, their positions go wrong on zoom.

I adjusted the sandbox so that the arrowheads are redrawn on moveend, so it looks nice now.  Here's the crucial code:

```
let arrowheads;

const drawArrowheads = () => {
  if (arrowheads) {
    arrowheads.remove();
  }

  const ghost = L.polyline(latlngs)
    .arrowheads({ color: "orange", size: "15000m" })
    .addTo(map);
  arrowheads = ghost.getArrowheads();
  ghost.remove();
  arrowheads.addTo(map);
};

drawArrowheads();

map.on("moveend", drawArrowheads);
```

### [Working Sandbox](https://codesandbox.io/s/leaflet-curve-w-arrowheads-g24b6?file=/src/index.js)
